Advanced data exploration jsonnet
Percona-Lab/grafonnet-lib pull request #17
Opened 2019-06-24 02:59 UTC by mrinal1209

add support for Advanced Data Exploration dashboard

@adivinho @puneet0191

2019-06-24 10:00 UTC, adivinho requested changes
It's not required to use the "Repeating" functionality.

![Screenshot_20190624_125837](https://user-images.githubusercontent.com/25184101/60010148-d92b0900-967f-11e9-9503-b76d8359d186.png)

2019-06-30 14:15 UTC, mrinal1209 commented
@adivinho please review the requested change

2019-07-01 10:17 UTC, adivinho approved these changes

2019-07-03 09:35 UTC, puneet0191 approved these changes

2019-07-22 10:51 UTC, merged