Mysql query response time jsonnet
Percona-Lab/grafonnet-lib pull request #27
Opened 2019-07-15 17:29 UTC by mrinal1209

Add support for MySQL Query Response Time Dashboard.

@adivinho @puneet0191

2019-07-15 20:19 UTC, adivinho requested changes
Please remove spaces in the text element.
![Screenshot_20190715_231534](https://user-images.githubusercontent.com/25184101/61246076-b65bb400-a756-11e9-97a1-344158022363.png)

Also no variable **Event** is used.
![Screenshot_20190715_231817](https://user-images.githubusercontent.com/25184101/61246152-dab79080-a756-11e9-9bc0-be8c903a9130.png)

2019-07-16 03:03 UTC, mrinal1209 commented
@adivinho please review the new changes

2019-07-16 19:15 UTC, adivinho approved these changes

2019-07-22 08:47 UTC, puneet0191 approved these changes

2019-07-23 20:07 UTC, merged