Mysql replication jsonnet
Percona-Lab/grafonnet-lib pull request #29
Opened 2019-07-17 17:47 UTC by mrinal1209

Add support for MySQL Replication Dashboard
@adivinho @puneet0191

2019-07-18 11:19 UTC, puneet0191 requested changes
Fix Conflicts

2019-07-18 11:51 UTC, adivinho commented
The singlestat "Host" has to have parameter Column = "node_name".
![Screenshot_20190718_144556](https://user-images.githubusercontent.com/25184101/61454903-d6fc5780-a96a-11e9-970f-7be15757db7b.png)

Please set parameter "Relative time" = 24h for next charts 
- "Binlog Data Written Hourly"
- "Binlogs Created Hourly"
- "Relay Log Written Hourly"

e.g.
![Screenshot_20190718_144844](https://user-images.githubusercontent.com/25184101/61455107-4d00be80-a96b-11e9-90c4-5b9f25a7f3d0.png)

2019-07-22 15:16 UTC, mrinal1209 commented
@adivinho @puneet0191  latest changes are made kindly review one more time

2019-07-24 17:20 UTC, adivinho approved these changes

2019-07-25 04:24 UTC, puneet0191 approved these changes

2019-07-25 07:23 UTC, merged