Mongo db cluster summary
Percona-Lab/grafonnet-lib pull request #33
Opened 2019-07-21 17:22 UTC by mrinal1209

Add support for MongoDB Cluster Summary Dashboard
@adivinho @puneet0191

2019-07-24 15:38 UTC, adivinho requested changes
Please enable the parameter "Hide time info" for all Singlestats.
![Screenshot_20190724_183634](https://user-images.githubusercontent.com/25184101/61807400-1aab0180-ae42-11e9-8286-bb0be742ca6b.png)

![Screenshot_20190724_183654](https://user-images.githubusercontent.com/25184101/61807403-1c74c500-ae42-11e9-8302-a8998bb0177c.png)

2019-07-24 20:23 UTC, adivinho commented
Now singlestats sizes are broken.

![Screenshot_20190724_232116](https://user-images.githubusercontent.com/25184101/61825919-fa8f3880-ae69-11e9-9915-b656c77034ee.png)

2019-07-25 04:24 UTC, puneet0191 requested changes
Fix

2019-07-25 09:52 UTC, adivinho approved these changes

2019-07-29 09:47 UTC, puneet0191 approved these changes

2019-07-29 09:48 UTC, merged