Mongo db mma pv1 jsonnet
Percona-Lab/grafonnet-lib pull request #34
Opened 2019-07-22 17:23 UTC by mrinal1209

Add support for MongoDB MMAPv1 Dashboard
@adivinho @puneet0191

2019-07-24 15:44 UTC, adivinho requested changes
Please enable parameter "Hide time info" for this singlestat.
![Screenshot_20190724_184244](https://user-images.githubusercontent.com/25184101/61807787-dec46c00-ae42-11e9-8000-5a9f3bcbf561.png)

The parameter "Scale" has to be "log (base 10)"
![Screenshot_20190724_184222](https://user-images.githubusercontent.com/25184101/61807816-f0a60f00-ae42-11e9-8b21-87f37f734ccc.png)

2019-07-25 04:24 UTC, puneet0191 requested changes
Fix

2019-07-25 04:26 UTC, mrinal1209 commented
> Fix

I already pushed the fix @puneet0191

2019-07-25 09:49 UTC, adivinho approved these changes

2019-07-29 09:47 UTC, puneet0191 approved these changes

2019-07-29 09:49 UTC, merged