Prometheus jsonnet
Percona-Lab/grafonnet-lib pull request #41
Opened 2019-08-08 17:03 UTC by mrinal1209

Add support for Prometheus Dashboard
@adivinho @puneet0191

2019-08-09 06:15 UTC, puneet0191 submitted a review, later dismissed

2019-08-09 07:32 UTC, adivinho requested changes
The parameter Legend is missed for the element "Top 10 metrics by time series count".
It has to be {{ __name__ }}
![Screenshot_20190809_102710](https://user-images.githubusercontent.com/25184101/62762072-ee71c080-ba90-11e9-8ee9-3aaf80de30e3.png)

Also please enable coloring for postfix in the element "Sys Uptime"
![Screenshot_20190809_102809](https://user-images.githubusercontent.com/25184101/62762090-f6316500-ba90-11e9-9335-92d531ac686a.png)

2019-08-12 07:12 UTC, puneet0191 approved these changes

2019-08-12 10:00 UTC, adivinho approved these changes

2019-08-12 10:04 UTC, merged