Mysql overview jsonnet
Percona-Lab/grafonnet-lib pull request #42
Opened 2019-08-11 07:00 UTC by mrinal1209

Add support for MySQL Overview Dashboard
@adivinho @puneet0191

2019-08-12 07:12 UTC, puneet0191 approved these changes

2019-08-12 07:13 UTC, puneet0191 requested changes
Fix Conflict

2019-08-12 10:36 UTC, adivinho approved these changes

2019-08-12 11:18 UTC, adivinho requested changes
There is one formula is missed.
![Screenshot_20190812_141557](https://user-images.githubusercontent.com/25184101/62861361-ea050c00-bd0b-11e9-93b3-7f1e24d4ec55.png)

It has to be chart "Query Cache Size" too.

![Screenshot_20190812_141710](https://user-images.githubusercontent.com/25184101/62861381-fdb07280-bd0b-11e9-94e2-b0b1629a1c52.png)

2019-08-12 13:33 UTC, adivinho approved these changes

2019-08-14 08:33 UTC, puneet0191 approved these changes

2019-08-14 13:56 UTC, merged