Add support for MySQL InnoDB Metrics Dashboard
Percona-Lab/grafonnet-lib pull request #49
Opened 2019-08-15 17:52 UTC by mrinal1209

Add support for MySQL InnoDB Metrics Dashboard
@puneet0191 @adivinho

2019-08-15 19:42 UTC, adivinho requested changes
I have found just a small oversight. Please add a symbol "space" at the end of the Legend "Time to Use Redo Log Space". It has to be the same with a regexp in override rule.
![Screenshot_20190815_223503](https://user-images.githubusercontent.com/25184101/63121486-3b7ff600-bfad-11e9-9d52-dffa3825bbca.png)

```
$ grep "Time to Use Redo Log Space" MySQL_InnoDB_Metrics.jsonnet 
          "Time to Use Redo Log Space ": "#447EBC"
          "alias": "Time to Use Redo Log Space ",
            legendFormat='Time to Use Redo Log Space',
```

2019-08-16 08:30 UTC, puneet0191 requested changes
Please update

2019-08-16 12:54 UTC, adivinho approved these changes

2019-08-20 04:56 UTC, puneet0191 approved these changes

2019-08-20 08:23 UTC, merged